Fix compilation error.
Fixes:

In file included from ./src/util/prec.hpp:98:0,
                 from ./src/data/action/set.cpp:9:
./src/util/index_map.hpp: In instantiation of ‘void IndexMap<Key, Value>::cloneFrom(const IndexMap<Key, Value>&) [with Key = boost::intrusive_ptr<Field>; Value = boost::intrusive_ptr<Value>]’:
./src/data/action/set.cpp:128:71:   required from here
./src/util/index_map.hpp:70:44: error: ‘push_back’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
    push_back(value ? value->clone() : value);
                                            ^
./src/util/index_map.hpp:70:44: note: declarations in dependent base ‘std::vector<boost::intrusive_ptr<Value>, std::allocator<boost::intrusive_ptr<Value> > >’ are not found by unqualified lookup
./src/util/index_map.hpp:70:44: note: use ‘this->push_back’ instead
make: *** [src/data/action/magicseteditor-set.o] Error 1